services:
  nfs:
    restart: always
    image: whatwewant/nfs:${SERVICE_NFS_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_NFS_PORT}:2049
    volumes:
      - ${SERVICE_NFS_DATA_DIR}:/data
      # - ${SERVICE_NFS_CONFIGS_DIR}:/configs
      
networks:
  default:
    external: true
    name: compose-ingress
